### PR TITLE
chore: 【翻译】更新翻译

### PR DESCRIPTION
**Pull request by starhcq**
更新翻译

Log: 【翻译】更新翻译
Bug: https://pms.uniontech.com/bug-view-189815.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
