### PR TITLE
chore: Update version to 6.0.8

### PR DESCRIPTION
**Pull request by starhcq**
1.更新翻译
  2.修复Ctrl+B加粗字体又新建文本笔记的问题
  相关PR：
  * https://github.com/linuxdeepin/deepin-voice-note/pull/78
  * https://github.com/linuxdeepin/deepin-voice-note/pull/79

Log: Update version to 6.0.8

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — COMMENTED** [review]
/+1

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
