### PR TITLE
fix: 修复主题设置为深色时，进度条依然显示为浅色

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 之前的版本没有按照设计进行背景颜色的设置

Log: 修复主题设置为深色时，进度条依然显示为浅色

Bug: https://pms.uniontech.com/bug-view-185269.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
