### PR TITLE
fix: 优化当前audioport的选用规则

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 优化当前audioport的选用规则

Log: 优化当前audioport的选用规则

Bug: https://pms.uniontech.com/bug-view-213189.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]

**Pull request merged**
