### PR TITLE
feat: 保存语音、重做快捷键替换

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 保存语音、重做快捷键替换

Log: 保存语音、重做快捷键替换

Task: https://pms.uniontech.com/task-view-241887.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
