### PR TITLE
chore: 调整音频端口可用范围

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 调整音频端口可用范围（unknow状态默认为可用）

Log: 调整音频端口可用范围

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
