### PR TITLE
fix: 修复语音记事本UI问题

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复语音记事本UI问题

Log: 修复语音记事本UI问题

Bug: https://pms.uniontech.com/bug-view-244879.html
     https://pms.uniontech.com/bug-view-244885.html
     https://pms.uniontech.com/bug-view-244897.html
     https://pms.uniontech.com/bug-view-244863.html
     https://pms.uniontech.com/bug-view-244877.html

### CODE REVIEW

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]

**Pull request merged**
