### PR TITLE
fix: 修复语音记事本无法输入语音，缺少依赖

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 缺少依赖导致无法录音

Log: 修复语音记事本无法输入语音，缺少依赖

Bug: https://pms.uniontech.com/bug-view-174925.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by heyumoAi — APPROVED** [review]
/+1

**Pull request merged**
