### PR TITLE
fix: 修复快捷键说明中未显示撤销和重做

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复快捷键说明中未显示撤销和重做

Log: 修复快捷键说明中未显示撤销和重做

Bug: https://pms.uniontech.com/bug-view-189215.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
