### PR TITLE
feat: 适配华为云，华为云无法正确获取声卡信息

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 适配华为云，华为云无法正确获取声卡信息，导致无法点击录音

Log: 适配华为云，华为云无法正确获取声卡信息

Bug: https://pms.uniontech.com/bug-view-180109.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
