### PR TITLE
fix: 新建笔记按钮位置不对

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 新建笔记按钮位置未与录制按钮对齐

Log: 新建笔记按钮位置不对

Bug: https://pms.uniontech.com/bug-view-173893.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by heyumoAi — APPROVED** [review]
/+1

**Pull request merged**
